### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by ghost** [Desklop/Voice_ChatBot#4]
Нужно положить акустическую модель в /usr/local/lib/python3.5/dist-packages/pocketsphinx/model. Подробнее про это можно найти в статье на хабре https://habr.com/post/351376/

P.S. Это ошибка не RHVoice, а PocketSphinx.

Просто положить файлы в такую же деректорию для python 3.6 не канает

**Comment by dbklim** [comment]
Я не знаю, как это будет для Python3.6. Возможно, там будет /usr/local/lib/**python3.6**/dist-packages/pocketsphinx/model, или /usr/local/lib/**python3**/dist-packages/pocketsphinx/model. Нужно смотреть конкретно по имеющимся папкам, либо в поиске найти папку pocketsphinx и посмотреть её расположение.

**Comment by ghost** [comment]
Это помогло
