### ISSUE TITLE
Pocketshinx

### ISSUE THREAD

**Issue by ghost** [Desklop/Voice_ChatBot#5]
При попытке использования вылазит ошибка, в чем косяк всё стоит верно!

python3 speech_to_text.py 
[i] Загрузка языковой модели... Traceback (most recent call last):
  File "speech_to_text.py", line 101, in <module>
    main()
  File "speech_to_text.py", line 94, in main
    sr = SpeechRecognitionclass('from_microphone')
  File "speech_to_text.py", line 45, in __init__
    dic=os.path.join(model_path, 'ru_bot.dic')
  File "/usr/local/lib/python3.6/dist-packages/pocketsphinx/__init__.py", line 208, in __init__
    super(LiveSpeech, self).__init__(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pocketsphinx/__init__.py", line 90, in __init__
    super(Pocketsphinx, self).__init__(config)
  File "/usr/local/lib/python3.6/dist-packages/pocketsphinx/pocketsphinx.py", line 275, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

**Comment by ghost** [comment]
Скорее всего ошибка где то здесь за что отвечает строчка
hmm=os.path.join(model_path, 'zero_ru.cd_cont_4000'),
???

**Comment by dbklim** [comment]
Я запускал этот код в виртуальной машине, в докер-контейнере, на просто отдельной машине и всё работало. Ищите ошибку у себя в путях.

`hmm=os.path.join(model_path, 'zero_ru.cd_cont_4000')` - эта строка отвечает за путь к акустической модели. Если у вас никак не получается положить её в требуемое место - скопируйте акустическую модель в папку с проектом и передайте полный путь к ней: `hmm=os.path.dirname(os.path.realpath(__file__)) + '/zero_ru.cd_cont_4000'`

UPD: Если смотреть по описанию ошибки - PocketSphinx не видит словарь. Вот эта строка об этом говорит: 
```
File "speech_to_text.py", line 45, in init
dic=os.path.join(model_path, 'ru_bot.dic')
```
Что бы исправить, сделайте с ней тоже самое, что и с акустической моделью (и перечитайте README.md, там есть этот момент - копирование акустической, языковой модели и словаря в нужное место).
