### ISSUE TITLE
Не запускается в докере

### ISSUE THREAD

**Issue by alexander-rykhlitskiy** [Desklop/Voice_ChatBot#7]
1. После запуска `docker build -t voice_chatbot:0.1 .` выводит
```
Step 19/41 : RUN unzip install_files/RHVoice.zip
 ---> Running in 673881a195c1
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
note:  install_files/RHVoice.zip may be a plain executable, not an archive
unzip:  cannot find zipfile directory in one of install_files/RHVoice.zip or
        install_files/RHVoice.zip.zip, and cannot find install_files/RHVoice.zip.ZIP, period.
```
2. Если закомментировать `Установка RHVoice`, билдится успешно, но при запуске контейнера пишет 
```
➜  Voice_ChatBot git:(master) ✗ docker run -ti --rm -p 5000:5000 voice_chatbot:0.1
Traceback (most recent call last):
  File "rest_server.py", line 30, in <module>
    from tensorflow import get_default_graph
ImportError: cannot import name 'get_default_graph'
```

**Comment by dbklim** [comment]
Укажите пожалуйста в Dockerfile версию `tensorflow==1.13.1`. Я в скором времени выпущу обновление репозитория, которое исправит все эти детские болячки (это был мой дипломный проект и я попросту не ожидал, что он заинтересует кого-то).

**Comment by alexander-rykhlitskiy** [comment]
К сожалению, появились другие ошибки :(
Но спасибо большое за ответ, буду ждать обновлений.

**Comment by dbklim** [comment]
Я в ближайшее время обновлю репо, что бы всё работало в текущем виде. Сейчас Git LFS убрал все мои старые файлы с данными для обучения и моделями (т.к. теперь у них ограничение на 1Гб данных, а у меня там файлов на 3Гб), и из-за этого проект просто не запускается. На данный момент я загружаю все данные на Google Диск и скоро предоставлю ссылку на загрузку.

**Comment by dbklim** [comment]
@alexander-rykhlitskiy теперь всё должно собираться и запускаться :)

**Comment by alexander-rykhlitskiy** [comment]
@Desklop Спасибо за помощь. В db90daa все еще падает
```
Step 11/32 : RUN /bin/bash -c "if [[ ! $(ls -A 'data') || ! -f 'install_files/RHVoice.zip' ]]; then ./install_files/download_train_data_and_models.sh && rm -rf data/converations_ru data/subtitles_ru data/plays_ru/*.npz data/plays_ru/*.pkl data/plays_ru/*.png; fi"
 ---> Running in 95ff615bfa05
ls: cannot access 'data': No such file or directory
/bin/bash: -c: line 0: unexpected token `||' in conditional command
/bin/bash: -c: line 0: syntax error near `|'
/bin/bash: -c: line 0: `if [[ !  || ! -f 'install_files/RHVoice.zip' ]]; then ./install_files/download_train_data_and_models.sh && rm -rf data/converations_ru data/subtitles_ru data/plays_ru/*.npz data/plays_ru/*.pkl data/plays_ru/*.png; fi'
The command '/bin/sh -c /bin/bash -c "if [[ ! $(ls -A 'data') || ! -f 'install_files/RHVoice.zip' ]]; then ./install_files/download_train_data_and_models.sh && rm -rf data/converations_ru data/subtitles_ru data/plays_ru/*.npz data/plays_ru/*.pkl data/plays_ru/*.png; fi"' returned a non-zero code: 1
```

**Comment by alexander-rykhlitskiy** [comment]
Удалил первое условие, запустилось, но потом опять ошибка 
```
Step 18/32 : RUN unzip install_files/RHVoice.zip
 ---> Running in 041ccf1e95ba
unzip:  cannot find or open install_files/RHVoice.zip, install_files/RHVoice.zip.zip or install_files/RHVoice.zip.ZIP.
The command '/bin/sh -c unzip install_files/RHVoice.zip' returned a non-zero code: 9
```

**Comment by dbklim** [comment]
Да, я только что это отловил, пофиксилось просто добавлением кавычек в строку на 11 шаге. Попробуйте ещё раз

Это условие проверяет наличие файлов для обучения и готовых моделей, и если их нет - скачивает их с google диска, я добавил этот пункт в требования к запуску в readme. Без них не запустится

**Comment by alexander-rykhlitskiy** [comment]
Чтобы избежать таких догих "Sending build context" и "COPY . /Voice_ChatBot", не думали использовать volume?

**Comment by dbklim** [comment]
Думал, сделаю позже. Сейчас основная проблема я думаю в том, что загрузка архива на 3.4 Гб с данными для работы может занять явно больше пары минут.

Может потом от word2vec уйду к fasttext и заранее предобученным моделям для него, что бы весь объём загрузки составлял только веса нейронной сети, а не вообще практически всё, что есть. Это сэкономит примерно 2.5Гб места

**Comment by alexander-rykhlitskiy** [comment]
Спасибо за помощь, в конце концов все запустилось.
Как думаете, это может значить, что модель переобучена?
```
Q: Ну как я выгляжу?
A: просто замечательно!
Q: как я выгляжу?
A: телосложения, как
```

**Comment by dbklim** [comment]
Да, очень на это похоже. Или может быть модель word2vec не очень хорошая, у которой "ну" оказывает сильное влияние.
